= tomcat-utils

some bash script for tomcat 

== setup-catalina-base

...

== depoly-to-tomcat

[source]
Usage: setup-catalina-base [OPTIONS]... WEBAPP... CONTEXT

[source]
Deploy webapp to tomcat. Deploying webapp to localhost on
Catalina engine is supported, tomcat CONTEXT version is not support 

[source]
  WEBAPP      can be war file 
  CONTEXT     must start with /, can has sub directory 
  -d, --dest        The destination directory the WEBAPP will be deployed to, 
                    if not set,DEFAULT is CATALINA_BASE/apps. 
  -b, --base        Overide the env CATALINA_BASE. If no CATALINA_BASE enviro 
                    -ment variable, CATALINA_BASE is set to CATALINA_HOME, If 
                    CATALINA_HOME enviroment variable is not set yet, error 
                    arise then exit +
  -h, --help        display this help and exit 

[source]
EXAMPLE 
    setup-catalina-base -d /var/apps -b /var/catalina_base  ~/example.war / 
    setup-catalina-base  ~/example.war  /api/v1.0 

