#!/bin/bash
usage(){
    echo "Usage: `basename ${0}` [OPTIONS]... DIRECTORY..."
    echo -e \
"
Make one or more tomcat CATALINA_BASE directory

  DIRECTORY         Destination DIRECTORY(s) for CATALINA_BASE

  -m, --home        Overides CATALINA_HOME environment variable. If
                    CATALINA_HOME environment variable is not set yet, error
                    arise then exit
  -u, --user        Set the owner of CATALINA_BASE DIRECTORY. If the bash
                    executor is not root, the option will be ignored.
                    In Some tomcat tarball, files in CATALINA_HOME/conf/
                    is readonly except creator, so su or sudo is needed,
                    in the case -u option is used to set owner of DIRECTORY
                    system path.
  -x                Really do the command! Without the option, NOT do
                    anything! display param, location and file for test
  -h, --help        display this help and exit

EXAMPLE
    `basename ${0}` -m /opt/tomcat ~/base1 -x
    `basename ${0}` ~/base1 ~/base2 ~/base3
    sudo `basename ${0}` ~/base1 -u foo
"
    exit 1
}

invalidopt(){
    echo "`basename ${0}`: invalid option ${1:+--'${1}'} ${2:+: ${2}}"
    echo "Try '`basename ${0}` --help' for more information"
    exit 1
}

invalidparam(){
    echo "`basename ${0}`: invalid parameters ${1:+--'${1}'} ${2:+: ${2}}"
    echo "Try '`basename ${0}` --help' for more information"
    exit 1
}

###################### parse positional parameters
while [[ $1 ]]; do
    case $1 in
        -m | --home )
            CATALINA_HOME=$2
            if [[ -z $2 ]]; then
                invalidopt $1 "must be followed by a path"
            else
                shift 2
            fi
            ;;
        -u | --user )
            DEST_OWNER=$2
            if [[ -z $2 ]]; then
                invalidopt $1 "must be followed by a username"
            else
                shift 2
            fi
            ;;
        -x )
            FLAG_DO="y"
            shift
            ;;
        -h | --help )
            usage
            break
            ;;
        -- ) # End of all options
            shift
            break
            ;;
        -* )
            invalidopt $1
            ;;
        * )
            DEST_CATALINA_BASES[${#DEST_CATALINA_BASES[@]}]=$1 #put in DEST_CATALINA_BASES array
            shift
           ;;
    esac
done

############# check CATALINA_HOME
if [[ -z $CATALINA_HOME ]]; then
    invalidopt "-m"  "-m CATALINA_HOME need be set, or set in environment variable"
fi

if [[ ${#DEST_CATALINA_BASES[@]} -eq 0 ]]; then
  invalidparam "" "must set at least one DIRECTORY"
fi

##################### check whether can not read tomcat conf
if [ ! -r $CATALINA_HOME/conf/server.xml ]; then
  invalidparam "" "conf files can not be read, use sudo or su to root"
fi

#################### check whether root user
if [[ $(id -u) -ne 0  ]]; then
  DEST_OWNER=""            #if not root , ignore -u option
fi

#################### prepare and display vairable
echo -e "CATALINA_HOME=\e[1m$CATALINA_HOME\e[0m"
echo -e "dest base(s)...=\e[1m${DEST_CATALINA_BASES[@]}\e[0m"
echo -e "DEST_OWNER=\e[1m${DEST_OWNER}\e[0m"

if [[ -z $FLAG_DO ]]; then
    echo -e "\e[1mNOT do anything!\e[0m display param, location and file for test"
    exit 0
fi

########### copy function
copyfrom_catalina_home(){
    DEST_BASE=${1}
    mkdir $DEST_BASE/conf -p
    cp $CATALINA_HOME/conf/* $DEST_BASE/conf
    mkdir $DEST_BASE/bin -p
    touch $DEST_BASE/bin/setenv.sh
    mkdir $DEST_BASE/lib -p
    mkdir $DEST_BASE/logs -p
    mkdir $DEST_BASE/temp -p
    mkdir $DEST_BASE/webapps -p
    mkdir $DEST_BASE/work -p
}

for i in ${DEST_CATALINA_BASES[@]}; do
    copyfrom_catalina_home $i
    if [[ ! -z $DEST_OWNER ]]; then
      chown ${DEST_OWNER}.$(id -ng ${DEST_OWNER}) $i -R
    fi
done
